codecov:
  require_ci_to_pass: false
  branch: main
  max_report_age: false

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    patch: false
    project:
      default: false
      devloperconnectapi:
        target: 80%
        flags:
          - devloperconnectapi
      devloperconnectui:
        target: 80%
        flags:
          - devloperconnectui
ignore:
  - "^/tests/**/*" # ignore test harness code

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: true

flags:
  devloperconnectrapi:
    paths:
      - api
    carryforward: true
  devloperconnectui:
    paths:
      - web/site
    carryforward: true
