name: API Gateway CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "web/site/**"

defaults:
  run:
    shell: bash
    working-directory: ./web/site

jobs:
  setup-job:
    runs-on: ubuntu-22.04

    if: github.repository == 'bcgov/sbc-apigw'

    steps:
      - uses: actions/checkout@v4
      - run: "true"

  linting:
    needs: setup-job
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.6.1]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: |
          pnpm install
      - name: build
        run: |
          pnpm run build-check
      - name: Linting
        run: |
          pnpm run lint

  testing-coverage:
    needs: setup-job
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.6.1]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: |
          pnpm install
      - name: Testing
        run: |
          pnpm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: apigw
          name: codecov-apigw
          fail_ci_if_error: true

  build-check:
    needs: setup-job
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.6.1]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: |
          pnpm install

      - name: run test
        run: |
          pnpm run build-check