name: Developer Connect UI CI

on:
  pull_request:
    paths:
      - "web/site/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./web/site

jobs:
  devloper-connect-ui-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-ci.yaml@main
    with:
      app_name: "devloper-connect-ui"
      working_directory: "./web/site"
      codecov_flag: "devloperconnectui"
